# Generated by Django 3.0.3 on 2020-02-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObjType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('hollis_id', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('shortdesc', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('objtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev.ObjType')),
            ],
        ),
    ]
