# Generated by Django 3.0.3 on 2020-02-28 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='hollis_id',
            new_name='hollis',
        ),
    ]
