# Generated by Django 3.0.3 on 2020-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0002_auto_20200228_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtype',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
