# Generated by Django 3.0.8 on 2022-09-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_objtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
