# Generated by Django 3.0.8 on 2022-10-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0004_device_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='objtype',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
