# Generated by Django 3.0.3 on 2020-02-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clean', models.TextField(blank=True, null=True)),
                ('check', models.TextField(blank=True, null=True)),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev.Device')),
            ],
        ),
    ]
