# Generated by Django 3.0.3 on 2020-02-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20200228_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceedure',
            name='check',
        ),
        migrations.RemoveField(
            model_name='proceedure',
            name='clean',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='components',
            field=models.ManyToManyField(blank=True, to='inv.Component'),
        ),
    ]
