# Generated by Django 3.0.3 on 2020-02-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20200228_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedure',
            name='clean',
            field=models.TextField(blank=True),
        ),
    ]
