# Generated by Django 3.0.3 on 2020-02-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_proceedure_clean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceedure',
            name='clean',
        ),
        migrations.AddField(
            model_name='proceedure',
            name='checking',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proceedure',
            name='cleaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
