# Generated by Django 3.0.3 on 2020-03-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20200228_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceedure',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
