# Generated by Django 3.0.3 on 2020-03-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_objtype_name'),
        ('inv', '0008_auto_20200302_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedure',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev.Device'),
        ),
    ]
