# Generated by Django 3.0.3 on 2020-03-02 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20200302_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceedure',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Inventory'),
        ),
    ]
