# Generated by Django 3.0.3 on 2020-03-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0011_auto_20200302_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='checking',
            field=models.ManyToManyField(blank=True, to='inv.Checking'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='cleaning',
            field=models.ManyToManyField(blank=True, to='inv.Cleaning'),
        ),
    ]
