# Generated by Django 3.0.3 on 2020-03-02 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_objtype_name'),
        ('inv', '0012_auto_20200302_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemInv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('checking', models.ManyToManyField(blank=True, to='inv.Checking')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='proceedure',
            name='name',
        ),
        migrations.RenameModel(
            old_name='Cleaning',
            new_name='Clean',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Proceedure',
        ),
        migrations.AddField(
            model_name='iteminv',
            name='clean',
            field=models.ManyToManyField(blank=True, to='inv.Clean'),
        ),
        migrations.AddField(
            model_name='iteminv',
            name='components',
            field=models.ManyToManyField(blank=True, to='inv.Component'),
        ),
        migrations.AddField(
            model_name='iteminv',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inv.Location'),
        ),
        migrations.AddField(
            model_name='iteminv',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev.Device'),
        ),
    ]
