# Generated by Django 3.0.3 on 2020-03-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0013_auto_20200302_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clean',
            old_name='cleaning',
            new_name='clean',
        ),
    ]
