# Generated by Django 3.0.3 on 2020-03-02 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0014_auto_20200302_1404'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clean',
            new_name='Cleaning',
        ),
        migrations.RenameField(
            model_name='cleaning',
            old_name='clean',
            new_name='cleaning',
        ),
        migrations.RenameField(
            model_name='iteminv',
            old_name='clean',
            new_name='cleaning',
        ),
    ]
