# Generated by Django 3.0.3 on 2020-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0015_auto_20200302_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checking',
            name='checking',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
