# Generated by Django 3.0.3 on 2020-03-02 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_objtype_name'),
        ('inv', '0016_auto_20200302_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ItemInv',
            new_name='Item',
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Item')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inv.Status')),
            ],
        ),
    ]
